### PR TITLE
Update OffensiveFlask() for Silver Flask 

### PR DESCRIPTION
**Pull request by yuwei111**
Read player buffs to see if Silver Flask are already in use or not.
Avoid using Sliver Flask after SpeedFlaskLogic in a short time.
It maybe one solution for TODO list: Each flask have it's own delay.

### CODE REVIEW

**Comment by zaafar** [comment]
@yuwei111 do it for all offensive flask or none.
Don't do it for just one offensive flask.

**Comment by zaafar** [comment]
If we do it like this, it break a feature known as 'drink all flask together'

**Comment by yuwei111** [comment]
@zaafar but  it's a serious waste of silver flask's charges.
or can we separate silver flask from OffensiveFlask, create a independent function for silver flask.

**Comment by zaafar** [comment]
@yuwei111  I agree with you on that, it's just that your approach isn't generic.
A generic approach would be like this.

http://i.imgur.com/DReU7nz.png

**Pull request closed without merging**
