### PR TITLE
Update LifeLogic, ManaLogic, and SpeedFlaskLogic

### PR DESCRIPTION
**Pull request by yuwei111**
1.LifeLogic
Avoid repeat use life flasks when effect working

2.ManaLogic
a.Avoid repeat use mana flasks when effect working
b.Add InstantManaFlask for using InstantMana&Mana flask together. Avoid can't use InstantMana when Mana flask in effect.
c.Add Menu Settings for InstantManaFlask .

3.Silver Flask for SpeedFlaskLogic 
a.Update SpeedFlaskLogic and OffensiveFlask
b.Add SilverFlask to FlaskAction
c.Update FlaskManagerSettings
d.Update flaskinfo

### CODE REVIEW

**Comment by zaafar** [comment]
@yuwei111 can you allow me push access to your REPO, i wanna do some changes to this PR.

**Comment by yuwei111** [comment]
sure, let me set it

**Comment by zaafar** [comment]
@yuwei111 done, check the changes I did there. :)

**Comment by zaafar** [comment]
@yuwei111 merging it right now, open a new PR if you feel like something is incorrect/there is a bug.
Right now I have tested it a bit and it's working good.

**Pull request merged**
